export const INIT = 'INIT'
export const ADD = 'ADD'
export const DELETE = 'DELETE'
export const EDIT = 'EDIT'
export const DONE = 'DONE'
export const SETUSER = 'SETUSER'
export const LOGOUT = 'LOGOUT'
